version: '3.5'

services:

    mysql:
        container_name: spring-boot-querydsl_mysql
        image: mysql:5.7.29
        environment:
            - MYSQL_DATABASE=spring-boot-querydsl_db
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3307:3306"
        restart: always

volumes:
    mysql_data:
        name: spring-boot-querydsl_mysql_data